import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { Topbar } from "@/components/Topbar";
import { menus } from "@/sanity/sanityQueries";
import { SanityDocument } from "next-sanity";
import { sanityFetch } from "@/sanity/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getData(): Promise<SanityDocument | null> {
  const query = menus();
  const data = await sanityFetch<SanityDocument>({ query });

  console.log("console menu", data);
  return data || null; // Retorna null se não houver dados
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getData();
  console.log("console do logo", data.logo);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Topbar />
        <Navbar logo={data.logo} menuItems={data.menuItems} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
