/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hGqapeEJi5x
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { topbar } from "@/app/queries"

type TopbarProps = {
  text: string;
}

export function Topbar() {
  const topbarData: TopbarProps = topbar[0];
  return (
    <div className="bg-primary text-primary-foreground py-2 px-4 text-center">
      <p className="text-sm font-medium">{topbarData.text}</p>
    </div>
  )
}
