/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/GeyURwRwJkY
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */


import ArrowRightIcon from "./ui/ArrowRightIcon";
import { Button } from "./ui/Button";
import { twoColumnsText } from "@/app/queries";

const { title, text1, text2, hasButton } = twoColumnsText[0];
interface TwoColumnsTextProps {
  title?: string;
  column1?: string;
  column2?: string;
  hasButton?: boolean;
}

export function TwoColumnsText() {
  return (
    <div className="container mx-auto px-4 md:px-6 py-12 md:py-24">
      <div className="grid grid-cols-1 gap-8">
        <div>
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">{title}</h2>
        </div>
        <div className="grid lg:grid-cols-2 gap-8">
          <div>
            <p className="text-muted-foreground">{text1}</p>
          </div>
          <div>
            <p className="text-muted-foreground">{text2}</p>
          </div>
        </div>
        {hasButton && (
          <Button variant="link" className="justify-end">
            Saiba Mais <ArrowRightIcon className="ml-1 w-4 h-4" />
          </Button>
        )}
      </div>
    </div>
  );
}
